// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: content.proto

package com.fxa.image.client.proto;

public final class ContentOuter {
  private ContentOuter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ContentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Content)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *发布者UID
     * </pre>
     *
     * <code>string author = 1;</code>
     * @return The author.
     */
    String getAuthor();
    /**
     * <pre>
     *发布者UID
     * </pre>
     *
     * <code>string author = 1;</code>
     * @return The bytes for author.
     */
    com.google.protobuf.ByteString
        getAuthorBytes();

    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    String getTitle();
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    com.google.protobuf.ByteString
        getTitleBytes();

    /**
     * <code>string content = 3;</code>
     * @return The content.
     */
    String getContent();
    /**
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    com.google.protobuf.ByteString
        getContentBytes();

    /**
     * <code>string image_url = 4;</code>
     * @return The imageUrl.
     */
    String getImageUrl();
    /**
     * <code>string image_url = 4;</code>
     * @return The bytes for imageUrl.
     */
    com.google.protobuf.ByteString
        getImageUrlBytes();

    /**
     * <pre>
     *图片热度 根据浏览量来设计一个策略 浏览量越多 分数越高
     * </pre>
     *
     * <code>int32 score = 5;</code>
     * @return The score.
     */
    int getScore();

    /**
     * <pre>
     *点赞数
     * </pre>
     *
     * <code>int64 like_cnt = 6;</code>
     * @return The likeCnt.
     */
    long getLikeCnt();

    /**
     * <pre>
     *浏览量
     * </pre>
     *
     * <code>int64 views = 7;</code>
     * @return The views.
     */
    long getViews();

    /**
     * <pre>
     *所属话题ID 一个或者多个
     * </pre>
     *
     * <code>repeated int32 topic = 8;</code>
     * @return A list containing the topic.
     */
    java.util.List<Integer> getTopicList();
    /**
     * <pre>
     *所属话题ID 一个或者多个
     * </pre>
     *
     * <code>repeated int32 topic = 8;</code>
     * @return The count of topic.
     */
    int getTopicCount();
    /**
     * <pre>
     *所属话题ID 一个或者多个
     * </pre>
     *
     * <code>repeated int32 topic = 8;</code>
     * @param index The index of the element to return.
     * @return The topic at the given index.
     */
    int getTopic(int index);

    /**
     * <pre>
     *图片分类ID，一个或者多个
     * </pre>
     *
     * <code>repeated int32 label = 9;</code>
     * @return A list containing the label.
     */
    java.util.List<Integer> getLabelList();
    /**
     * <pre>
     *图片分类ID，一个或者多个
     * </pre>
     *
     * <code>repeated int32 label = 9;</code>
     * @return The count of label.
     */
    int getLabelCount();
    /**
     * <pre>
     *图片分类ID，一个或者多个
     * </pre>
     *
     * <code>repeated int32 label = 9;</code>
     * @param index The index of the element to return.
     * @return The label at the given index.
     */
    int getLabel(int index);
  }
  /**
   * Protobuf type {@code Content}
   */
  public static final class Content extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Content)
      ContentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Content.newBuilder() to construct.
    private Content(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Content() {
      author_ = "";
      title_ = "";
      content_ = "";
      imageUrl_ = "";
      topic_ = emptyIntList();
      label_ = emptyIntList();
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Content();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Content(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              author_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              title_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              content_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              imageUrl_ = s;
              break;
            }
            case 40: {

              score_ = input.readInt32();
              break;
            }
            case 48: {

              likeCnt_ = input.readInt64();
              break;
            }
            case 56: {

              views_ = input.readInt64();
              break;
            }
            case 64: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                topic_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              topic_.addInt(input.readInt32());
              break;
            }
            case 66: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) != 0) && input.getBytesUntilLimit() > 0) {
                topic_ = newIntList();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                topic_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            case 72: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                label_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              label_.addInt(input.readInt32());
              break;
            }
            case 74: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000002) != 0) && input.getBytesUntilLimit() > 0) {
                label_ = newIntList();
                mutable_bitField0_ |= 0x00000002;
              }
              while (input.getBytesUntilLimit() > 0) {
                label_.addInt(input.readInt32());
              }
              input.popLimit(limit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          topic_.makeImmutable(); // C
        }
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          label_.makeImmutable(); // C
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ContentOuter.internal_static_Content_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ContentOuter.internal_static_Content_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Content.class, Builder.class);
    }

    public static final int AUTHOR_FIELD_NUMBER = 1;
    private volatile Object author_;
    /**
     * <pre>
     *发布者UID
     * </pre>
     *
     * <code>string author = 1;</code>
     * @return The author.
     */
    @Override
    public String getAuthor() {
      Object ref = author_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        author_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *发布者UID
     * </pre>
     *
     * <code>string author = 1;</code>
     * @return The bytes for author.
     */
    @Override
    public com.google.protobuf.ByteString
        getAuthorBytes() {
      Object ref = author_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        author_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TITLE_FIELD_NUMBER = 2;
    private volatile Object title_;
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    @Override
    public String getTitle() {
      Object ref = title_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        title_ = s;
        return s;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    @Override
    public com.google.protobuf.ByteString
        getTitleBytes() {
      Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 3;
    private volatile Object content_;
    /**
     * <code>string content = 3;</code>
     * @return The content.
     */
    @Override
    public String getContent() {
      Object ref = content_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        content_ = s;
        return s;
      }
    }
    /**
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    @Override
    public com.google.protobuf.ByteString
        getContentBytes() {
      Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMAGE_URL_FIELD_NUMBER = 4;
    private volatile Object imageUrl_;
    /**
     * <code>string image_url = 4;</code>
     * @return The imageUrl.
     */
    @Override
    public String getImageUrl() {
      Object ref = imageUrl_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        imageUrl_ = s;
        return s;
      }
    }
    /**
     * <code>string image_url = 4;</code>
     * @return The bytes for imageUrl.
     */
    @Override
    public com.google.protobuf.ByteString
        getImageUrlBytes() {
      Object ref = imageUrl_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        imageUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SCORE_FIELD_NUMBER = 5;
    private int score_;
    /**
     * <pre>
     *图片热度 根据浏览量来设计一个策略 浏览量越多 分数越高
     * </pre>
     *
     * <code>int32 score = 5;</code>
     * @return The score.
     */
    @Override
    public int getScore() {
      return score_;
    }

    public static final int LIKE_CNT_FIELD_NUMBER = 6;
    private long likeCnt_;
    /**
     * <pre>
     *点赞数
     * </pre>
     *
     * <code>int64 like_cnt = 6;</code>
     * @return The likeCnt.
     */
    @Override
    public long getLikeCnt() {
      return likeCnt_;
    }

    public static final int VIEWS_FIELD_NUMBER = 7;
    private long views_;
    /**
     * <pre>
     *浏览量
     * </pre>
     *
     * <code>int64 views = 7;</code>
     * @return The views.
     */
    @Override
    public long getViews() {
      return views_;
    }

    public static final int TOPIC_FIELD_NUMBER = 8;
    private com.google.protobuf.Internal.IntList topic_;
    /**
     * <pre>
     *所属话题ID 一个或者多个
     * </pre>
     *
     * <code>repeated int32 topic = 8;</code>
     * @return A list containing the topic.
     */
    @Override
    public java.util.List<Integer>
        getTopicList() {
      return topic_;
    }
    /**
     * <pre>
     *所属话题ID 一个或者多个
     * </pre>
     *
     * <code>repeated int32 topic = 8;</code>
     * @return The count of topic.
     */
    public int getTopicCount() {
      return topic_.size();
    }
    /**
     * <pre>
     *所属话题ID 一个或者多个
     * </pre>
     *
     * <code>repeated int32 topic = 8;</code>
     * @param index The index of the element to return.
     * @return The topic at the given index.
     */
    public int getTopic(int index) {
      return topic_.getInt(index);
    }
    private int topicMemoizedSerializedSize = -1;

    public static final int LABEL_FIELD_NUMBER = 9;
    private com.google.protobuf.Internal.IntList label_;
    /**
     * <pre>
     *图片分类ID，一个或者多个
     * </pre>
     *
     * <code>repeated int32 label = 9;</code>
     * @return A list containing the label.
     */
    @Override
    public java.util.List<Integer>
        getLabelList() {
      return label_;
    }
    /**
     * <pre>
     *图片分类ID，一个或者多个
     * </pre>
     *
     * <code>repeated int32 label = 9;</code>
     * @return The count of label.
     */
    public int getLabelCount() {
      return label_.size();
    }
    /**
     * <pre>
     *图片分类ID，一个或者多个
     * </pre>
     *
     * <code>repeated int32 label = 9;</code>
     * @param index The index of the element to return.
     * @return The label at the given index.
     */
    public int getLabel(int index) {
      return label_.getInt(index);
    }
    private int labelMemoizedSerializedSize = -1;

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (!getAuthorBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, author_);
      }
      if (!getTitleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, title_);
      }
      if (!getContentBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, content_);
      }
      if (!getImageUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, imageUrl_);
      }
      if (score_ != 0) {
        output.writeInt32(5, score_);
      }
      if (likeCnt_ != 0L) {
        output.writeInt64(6, likeCnt_);
      }
      if (views_ != 0L) {
        output.writeInt64(7, views_);
      }
      if (getTopicList().size() > 0) {
        output.writeUInt32NoTag(66);
        output.writeUInt32NoTag(topicMemoizedSerializedSize);
      }
      for (int i = 0; i < topic_.size(); i++) {
        output.writeInt32NoTag(topic_.getInt(i));
      }
      if (getLabelList().size() > 0) {
        output.writeUInt32NoTag(74);
        output.writeUInt32NoTag(labelMemoizedSerializedSize);
      }
      for (int i = 0; i < label_.size(); i++) {
        output.writeInt32NoTag(label_.getInt(i));
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getAuthorBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, author_);
      }
      if (!getTitleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, title_);
      }
      if (!getContentBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, content_);
      }
      if (!getImageUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, imageUrl_);
      }
      if (score_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, score_);
      }
      if (likeCnt_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, likeCnt_);
      }
      if (views_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, views_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < topic_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(topic_.getInt(i));
        }
        size += dataSize;
        if (!getTopicList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        topicMemoizedSerializedSize = dataSize;
      }
      {
        int dataSize = 0;
        for (int i = 0; i < label_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(label_.getInt(i));
        }
        size += dataSize;
        if (!getLabelList().isEmpty()) {
          size += 1;
          size += com.google.protobuf.CodedOutputStream
              .computeInt32SizeNoTag(dataSize);
        }
        labelMemoizedSerializedSize = dataSize;
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Content)) {
        return super.equals(obj);
      }
      Content other = (Content) obj;

      if (!getAuthor()
          .equals(other.getAuthor())) return false;
      if (!getTitle()
          .equals(other.getTitle())) return false;
      if (!getContent()
          .equals(other.getContent())) return false;
      if (!getImageUrl()
          .equals(other.getImageUrl())) return false;
      if (getScore()
          != other.getScore()) return false;
      if (getLikeCnt()
          != other.getLikeCnt()) return false;
      if (getViews()
          != other.getViews()) return false;
      if (!getTopicList()
          .equals(other.getTopicList())) return false;
      if (!getLabelList()
          .equals(other.getLabelList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AUTHOR_FIELD_NUMBER;
      hash = (53 * hash) + getAuthor().hashCode();
      hash = (37 * hash) + TITLE_FIELD_NUMBER;
      hash = (53 * hash) + getTitle().hashCode();
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContent().hashCode();
      hash = (37 * hash) + IMAGE_URL_FIELD_NUMBER;
      hash = (53 * hash) + getImageUrl().hashCode();
      hash = (37 * hash) + SCORE_FIELD_NUMBER;
      hash = (53 * hash) + getScore();
      hash = (37 * hash) + LIKE_CNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLikeCnt());
      hash = (37 * hash) + VIEWS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getViews());
      if (getTopicCount() > 0) {
        hash = (37 * hash) + TOPIC_FIELD_NUMBER;
        hash = (53 * hash) + getTopicList().hashCode();
      }
      if (getLabelCount() > 0) {
        hash = (37 * hash) + LABEL_FIELD_NUMBER;
        hash = (53 * hash) + getLabelList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Content parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Content parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Content parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Content parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Content parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Content parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Content parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Content parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Content parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Content parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Content parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Content parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Content prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Content}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Content)
        ContentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ContentOuter.internal_static_Content_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ContentOuter.internal_static_Content_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Content.class, Builder.class);
      }

      // Construct using com.fxa.image.client.proto.publish.ContentOuter.Content.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        author_ = "";

        title_ = "";

        content_ = "";

        imageUrl_ = "";

        score_ = 0;

        likeCnt_ = 0L;

        views_ = 0L;

        topic_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        label_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ContentOuter.internal_static_Content_descriptor;
      }

      @Override
      public Content getDefaultInstanceForType() {
        return Content.getDefaultInstance();
      }

      @Override
      public Content build() {
        Content result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Content buildPartial() {
        Content result = new Content(this);
        int from_bitField0_ = bitField0_;
        result.author_ = author_;
        result.title_ = title_;
        result.content_ = content_;
        result.imageUrl_ = imageUrl_;
        result.score_ = score_;
        result.likeCnt_ = likeCnt_;
        result.views_ = views_;
        if (((bitField0_ & 0x00000001) != 0)) {
          topic_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.topic_ = topic_;
        if (((bitField0_ & 0x00000002) != 0)) {
          label_.makeImmutable();
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.label_ = label_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Content) {
          return mergeFrom((Content)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Content other) {
        if (other == Content.getDefaultInstance()) return this;
        if (!other.getAuthor().isEmpty()) {
          author_ = other.author_;
          onChanged();
        }
        if (!other.getTitle().isEmpty()) {
          title_ = other.title_;
          onChanged();
        }
        if (!other.getContent().isEmpty()) {
          content_ = other.content_;
          onChanged();
        }
        if (!other.getImageUrl().isEmpty()) {
          imageUrl_ = other.imageUrl_;
          onChanged();
        }
        if (other.getScore() != 0) {
          setScore(other.getScore());
        }
        if (other.getLikeCnt() != 0L) {
          setLikeCnt(other.getLikeCnt());
        }
        if (other.getViews() != 0L) {
          setViews(other.getViews());
        }
        if (!other.topic_.isEmpty()) {
          if (topic_.isEmpty()) {
            topic_ = other.topic_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTopicIsMutable();
            topic_.addAll(other.topic_);
          }
          onChanged();
        }
        if (!other.label_.isEmpty()) {
          if (label_.isEmpty()) {
            label_ = other.label_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureLabelIsMutable();
            label_.addAll(other.label_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Content parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Content) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Object author_ = "";
      /**
       * <pre>
       *发布者UID
       * </pre>
       *
       * <code>string author = 1;</code>
       * @return The author.
       */
      public String getAuthor() {
        Object ref = author_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          author_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <pre>
       *发布者UID
       * </pre>
       *
       * <code>string author = 1;</code>
       * @return The bytes for author.
       */
      public com.google.protobuf.ByteString
          getAuthorBytes() {
        Object ref = author_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          author_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *发布者UID
       * </pre>
       *
       * <code>string author = 1;</code>
       * @param value The author to set.
       * @return This builder for chaining.
       */
      public Builder setAuthor(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        author_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发布者UID
       * </pre>
       *
       * <code>string author = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAuthor() {
        
        author_ = getDefaultInstance().getAuthor();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *发布者UID
       * </pre>
       *
       * <code>string author = 1;</code>
       * @param value The bytes for author to set.
       * @return This builder for chaining.
       */
      public Builder setAuthorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        author_ = value;
        onChanged();
        return this;
      }

      private Object title_ = "";
      /**
       * <code>string title = 2;</code>
       * @return The title.
       */
      public String getTitle() {
        Object ref = title_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          title_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @return The bytes for title.
       */
      public com.google.protobuf.ByteString
          getTitleBytes() {
        Object ref = title_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          title_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string title = 2;</code>
       * @param value The title to set.
       * @return This builder for chaining.
       */
      public Builder setTitle(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        title_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTitle() {
        
        title_ = getDefaultInstance().getTitle();
        onChanged();
        return this;
      }
      /**
       * <code>string title = 2;</code>
       * @param value The bytes for title to set.
       * @return This builder for chaining.
       */
      public Builder setTitleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        title_ = value;
        onChanged();
        return this;
      }

      private Object content_ = "";
      /**
       * <code>string content = 3;</code>
       * @return The content.
       */
      public String getContent() {
        Object ref = content_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          content_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       * @return The bytes for content.
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string content = 3;</code>
       * @param value The content to set.
       * @return This builder for chaining.
       */
      public Builder setContent(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearContent() {
        
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>string content = 3;</code>
       * @param value The bytes for content to set.
       * @return This builder for chaining.
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        content_ = value;
        onChanged();
        return this;
      }

      private Object imageUrl_ = "";
      /**
       * <code>string image_url = 4;</code>
       * @return The imageUrl.
       */
      public String getImageUrl() {
        Object ref = imageUrl_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          imageUrl_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string image_url = 4;</code>
       * @return The bytes for imageUrl.
       */
      public com.google.protobuf.ByteString
          getImageUrlBytes() {
        Object ref = imageUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          imageUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string image_url = 4;</code>
       * @param value The imageUrl to set.
       * @return This builder for chaining.
       */
      public Builder setImageUrl(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        imageUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string image_url = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearImageUrl() {
        
        imageUrl_ = getDefaultInstance().getImageUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string image_url = 4;</code>
       * @param value The bytes for imageUrl to set.
       * @return This builder for chaining.
       */
      public Builder setImageUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        imageUrl_ = value;
        onChanged();
        return this;
      }

      private int score_ ;
      /**
       * <pre>
       *图片热度 根据浏览量来设计一个策略 浏览量越多 分数越高
       * </pre>
       *
       * <code>int32 score = 5;</code>
       * @return The score.
       */
      @Override
      public int getScore() {
        return score_;
      }
      /**
       * <pre>
       *图片热度 根据浏览量来设计一个策略 浏览量越多 分数越高
       * </pre>
       *
       * <code>int32 score = 5;</code>
       * @param value The score to set.
       * @return This builder for chaining.
       */
      public Builder setScore(int value) {
        
        score_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *图片热度 根据浏览量来设计一个策略 浏览量越多 分数越高
       * </pre>
       *
       * <code>int32 score = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearScore() {
        
        score_ = 0;
        onChanged();
        return this;
      }

      private long likeCnt_ ;
      /**
       * <pre>
       *点赞数
       * </pre>
       *
       * <code>int64 like_cnt = 6;</code>
       * @return The likeCnt.
       */
      @Override
      public long getLikeCnt() {
        return likeCnt_;
      }
      /**
       * <pre>
       *点赞数
       * </pre>
       *
       * <code>int64 like_cnt = 6;</code>
       * @param value The likeCnt to set.
       * @return This builder for chaining.
       */
      public Builder setLikeCnt(long value) {
        
        likeCnt_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *点赞数
       * </pre>
       *
       * <code>int64 like_cnt = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearLikeCnt() {
        
        likeCnt_ = 0L;
        onChanged();
        return this;
      }

      private long views_ ;
      /**
       * <pre>
       *浏览量
       * </pre>
       *
       * <code>int64 views = 7;</code>
       * @return The views.
       */
      @Override
      public long getViews() {
        return views_;
      }
      /**
       * <pre>
       *浏览量
       * </pre>
       *
       * <code>int64 views = 7;</code>
       * @param value The views to set.
       * @return This builder for chaining.
       */
      public Builder setViews(long value) {
        
        views_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *浏览量
       * </pre>
       *
       * <code>int64 views = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearViews() {
        
        views_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList topic_ = emptyIntList();
      private void ensureTopicIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          topic_ = mutableCopy(topic_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       *所属话题ID 一个或者多个
       * </pre>
       *
       * <code>repeated int32 topic = 8;</code>
       * @return A list containing the topic.
       */
      public java.util.List<Integer>
          getTopicList() {
        return ((bitField0_ & 0x00000001) != 0) ?
                 java.util.Collections.unmodifiableList(topic_) : topic_;
      }
      /**
       * <pre>
       *所属话题ID 一个或者多个
       * </pre>
       *
       * <code>repeated int32 topic = 8;</code>
       * @return The count of topic.
       */
      public int getTopicCount() {
        return topic_.size();
      }
      /**
       * <pre>
       *所属话题ID 一个或者多个
       * </pre>
       *
       * <code>repeated int32 topic = 8;</code>
       * @param index The index of the element to return.
       * @return The topic at the given index.
       */
      public int getTopic(int index) {
        return topic_.getInt(index);
      }
      /**
       * <pre>
       *所属话题ID 一个或者多个
       * </pre>
       *
       * <code>repeated int32 topic = 8;</code>
       * @param index The index to set the value at.
       * @param value The topic to set.
       * @return This builder for chaining.
       */
      public Builder setTopic(
          int index, int value) {
        ensureTopicIsMutable();
        topic_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *所属话题ID 一个或者多个
       * </pre>
       *
       * <code>repeated int32 topic = 8;</code>
       * @param value The topic to add.
       * @return This builder for chaining.
       */
      public Builder addTopic(int value) {
        ensureTopicIsMutable();
        topic_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *所属话题ID 一个或者多个
       * </pre>
       *
       * <code>repeated int32 topic = 8;</code>
       * @param values The topic to add.
       * @return This builder for chaining.
       */
      public Builder addAllTopic(
          Iterable<? extends Integer> values) {
        ensureTopicIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, topic_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *所属话题ID 一个或者多个
       * </pre>
       *
       * <code>repeated int32 topic = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearTopic() {
        topic_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      private com.google.protobuf.Internal.IntList label_ = emptyIntList();
      private void ensureLabelIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          label_ = mutableCopy(label_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <pre>
       *图片分类ID，一个或者多个
       * </pre>
       *
       * <code>repeated int32 label = 9;</code>
       * @return A list containing the label.
       */
      public java.util.List<Integer>
          getLabelList() {
        return ((bitField0_ & 0x00000002) != 0) ?
                 java.util.Collections.unmodifiableList(label_) : label_;
      }
      /**
       * <pre>
       *图片分类ID，一个或者多个
       * </pre>
       *
       * <code>repeated int32 label = 9;</code>
       * @return The count of label.
       */
      public int getLabelCount() {
        return label_.size();
      }
      /**
       * <pre>
       *图片分类ID，一个或者多个
       * </pre>
       *
       * <code>repeated int32 label = 9;</code>
       * @param index The index of the element to return.
       * @return The label at the given index.
       */
      public int getLabel(int index) {
        return label_.getInt(index);
      }
      /**
       * <pre>
       *图片分类ID，一个或者多个
       * </pre>
       *
       * <code>repeated int32 label = 9;</code>
       * @param index The index to set the value at.
       * @param value The label to set.
       * @return This builder for chaining.
       */
      public Builder setLabel(
          int index, int value) {
        ensureLabelIsMutable();
        label_.setInt(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *图片分类ID，一个或者多个
       * </pre>
       *
       * <code>repeated int32 label = 9;</code>
       * @param value The label to add.
       * @return This builder for chaining.
       */
      public Builder addLabel(int value) {
        ensureLabelIsMutable();
        label_.addInt(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *图片分类ID，一个或者多个
       * </pre>
       *
       * <code>repeated int32 label = 9;</code>
       * @param values The label to add.
       * @return This builder for chaining.
       */
      public Builder addAllLabel(
          Iterable<? extends Integer> values) {
        ensureLabelIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, label_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       *图片分类ID，一个或者多个
       * </pre>
       *
       * <code>repeated int32 label = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearLabel() {
        label_ = emptyIntList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Content)
    }

    // @@protoc_insertion_point(class_scope:Content)
    private static final Content DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Content();
    }

    public static Content getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Content>
        PARSER = new com.google.protobuf.AbstractParser<Content>() {
      @Override
      public Content parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Content(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Content> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Content> getParserForType() {
      return PARSER;
    }

    @Override
    public Content getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Content_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Content_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rcontent.proto\"\232\001\n\007Content\022\016\n\006author\030\001 " +
      "\001(\t\022\r\n\005title\030\002 \001(\t\022\017\n\007content\030\003 \001(\t\022\021\n\ti" +
      "mage_url\030\004 \001(\t\022\r\n\005score\030\005 \001(\005\022\020\n\010like_cn" +
      "t\030\006 \001(\003\022\r\n\005views\030\007 \001(\003\022\r\n\005topic\030\010 \003(\005\022\r\n" +
      "\005label\030\t \003(\005B2\n\"com.fxa.image.client.pro" +
      "to.publishB\014ContentOuterb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Content_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Content_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Content_descriptor,
        new String[] { "Author", "Title", "Content", "ImageUrl", "Score", "LikeCnt", "Views", "Topic", "Label", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
